#!/bin/sh

if [ ! $2 ]; then
	docker run --rm -it -v $(pwd):/mount $1 $2 $3 $4 $5 $6 $7 $8 $9
else
	if [ -f $2 ]; then
		docker run --rm -it -v $(pwd):/mount $1 /mount/$2 $3 $4 $5 $6 $7 $8 $9
	else
		docker run --rm -it -v $(pwd):/mount $@
	fi
fi
